USE `MEDAPP`;

CREATE TABLE `PATIENTS` (
`ID` INT(5) NOT NULL AUTO_INCREMENT,
`NAME` VARCHAR(40) NOT NULL,
`AGE` INT(3) NOT NULL,
`BLOODGROUP` VARCHAR(5) NOT NULL,
`PHONE` VARCHAR(15) NOT NULL,
`EMAIL` VARCHAR(30) NOT NULL,
`LOCATION` VARCHAR(20) NOT NULL,
PRIMARY KEY(`ID`)
);

INSERT INTO `medapp`.`patients`
(`NAME`,
`AGE`,
`BLOODGROUP`,
`PHONE`,
`EMAIL`,
`LOCATION`)
VALUES
('John',
'32',
'A+',
'9840948033',
'someone@something.com',
'Mars');
