CREATE DATABASE `MEDAPP`;
USE `MEDAPP`;

CREATE TABLE `ACCOUNTS` (
`ID` INT(5) NOT NULL AUTO_INCREMENT,
`USERNAME` VARCHAR(40) NOT NULL,
`PASSWORD` VARCHAR(20) NOT NULL,
PRIMARY KEY(`ID`)
);

INSERT INTO `medapp`.`accounts`
(`USERNAME`,
`PASSWORD`)
VALUES
('User1',
'123');


INSERT INTO accounts(`ID`,`USERNAME`,`PASSWORD`) VALUES ('1','admin','987654321');

SELECT * FROM accounts WHERE username = 'Nikhil' AND password = '987654321'
